from __future__ import annotations

from pathlib import Path
import tomllib

from gasecagent import __version__
from gasecagent.config import PROJECT_ROOT


def _example_environment() -> dict[str, str]:
    values: dict[str, str] = {}
    for line in (PROJECT_ROOT / ".env.example").read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        name, value = stripped.split("=", 1)
        values[name] = value
    return values


def test_release_version_and_license_are_consistent() -> None:
    metadata = tomllib.loads(
        (PROJECT_ROOT / "pyproject.toml").read_text(encoding="utf-8")
    )["project"]

    assert metadata["version"] == __version__ == "0.1.0"
    assert metadata["license"] == "MIT"
    license_text = (PROJECT_ROOT / "LICENSE").read_text(encoding="utf-8")
    assert "Copyright (c) 2026 GAlun" in license_text


def test_release_examples_do_not_contain_secrets() -> None:
    environment = _example_environment()

    assert environment["GA_FILESYSTEM_ROOT"] == "workspace"
    for name in (
        "GA_LLM_API_KEY",
        "GA_EMBEDDING_API_KEY",
        "TAVILY_API_KEY",
        "FOFA_KEY",
    ):
        assert environment[name] == ""

    mcp_example = (PROJECT_ROOT / "mcp.example.json").read_text(encoding="utf-8")
    assert '"TAVILY_API_KEY": "${TAVILY_API_KEY}"' in mcp_example
    assert '"FOFA_KEY": "${FOFA_KEY}"' in mcp_example


def test_requirements_are_exported_from_the_lock() -> None:
    requirements = (PROJECT_ROOT / "requirements.txt").read_text(encoding="utf-8")

    assert "autogenerated by uv" in requirements
    for dependency in (
        "httpx==0.28.1",
        "mcp==1.30.0",
        "numpy==2.3.5",
        "openai==3.19.0",
        "openai-agents==0.22.3",
        "python-dotenv==1.2.3",
        "rich==15.0.0",
    ):
        assert dependency in requirements
